### PR TITLE
docs(PageTracking): Add docs for createInstance

### PR DESCRIPTION
**Pull request by parlarjb**
JIRA: https://jira.rax.io/browse/FRMW-707

### LGTMs
- [x] Dev LGTM
- [x] Dev LGTM

### CODE REVIEW

**Comment by parlarjb** [comment]
screen shot 2016-04-20 at 2 19 16 pm

**Comment by parlarjb** [comment]
## Before 

screen shot 2016-04-20 at 2 22 01 pm

**Comment by parlarjb** [comment]
## After

screen shot 2016-04-20 at 2 19 16 pm

**Comment by CITguy** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Pull request merged**
