### PR TITLE
chore(node): Offical support for node v5

### PR DESCRIPTION
**Pull request by Droogans**
Let's see what happens here.

- [x] Dev LGTM
- [x] QE LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
Please update the version in `.node-version`.

**Comment by Droogans** [comment]
I'm not sure what you mean by that. Can you be more specific?

**Comment by CITguy** [comment]
https://github.com/rackerlabs/encore-ui/blob/master/.node-version should also be `5.1.1`

**Comment by CITguy** [comment]
LGTM

**Comment by Droogans** [comment]
@jj4th can I get a QE LGTM?

**Comment by jj4th** [comment]
yup

**Pull request merged**
