### PR TITLE
refactor(Auth): FRMW-370 convert to Quark Service.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-370

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxAuth.Auth` to Quark Service.  This PR removes `rxAuth` component.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `Auth` Quark Service

### Demo Page
screen shot 2016-02-11 at 10 36 50 am


### API Docs
screen shot 2016-02-11 at 10 37 14 am

**Comment by CITguy** [comment]
LGTM

**Comment by glynnis** [comment]
Design LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
