### PR TITLE
refactor(rxBreadcrumbsSvc): move to Quarks

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-388

### LGTMs
- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
screen shot 2015-12-09 at 2 43 46 pm

screen shot 2015-12-09 at 2 43 58 pm

**Comment by ssalinas24** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
