### PR TITLE
fix(rxForm): correct invalid styles for rxCharacterCount

### PR DESCRIPTION
**Pull request by CITguy**
Correction for invalid styles with regards to rxCharacterCount

### LGTMS
- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

#### Links
* https://jira.rax.io/browse/FRMW-92

### CODE REVIEW

**Comment by bry4n** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Comment by CITguy** [comment]
## Before

### Initial Load (clean form)
* Error message should not be displayed
* No red border on Text Area
prod-rxform-loaded

### Text Added (dirty form, field valid)
* Displays correctly (no error message, no red border)
local-rxform-addedtext

### Text Removed (dirty form, field invalid)
* Error message displays
* Text Area should have red border
prod-rxform-removedtext


## After

### Initial Load (clean form)
* No error message
* No red border on Text Area
local-rxform-loaded

### Text Added (dirty form, field valid)
* No error message
* No red border on Text Area
local-rxform-addedtext

### Text Removed (dirty form, field invalid)
* Error message displays
* Text Area has red border
local-rxform-removedtext

**Comment by glynnis** [comment]
Based on screen shots, LGTM :+1:

**Pull request merged**
