### PR TITLE
docs(copy_edits): FRMW-267-Typography-copy-edits

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-267 - SPIKE: Basics - Typography

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

**Copy Edits** to `Typography` styleguide

### CODE REVIEW

**Comment by 100stacks** [comment]
screen shot 2015-10-09 at 10 03 11 am

**Comment by bry4n** [comment]
LGTM

**Comment by CITguy** [comment]
Honestly, the second bullet point would be moot if we just used a CSS import in `src/rxApp/common.less` to import the font. Then all the consuming apps need to have is the link to the generated `encore-ui.css` or `encore-ui-resp.css` file.

**src/rxApp/common.less** (first `@import` of the file)
```
@import url("https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,700,700italic");
```

Then change the bullet points to read:

> * We use Google Fonts, in particular the Roboto font. This is automatically imported via CSS when you link `encore-ui.css` or `encore-ui-resp.css`.

**Comment by 100stacks** [comment]
@CITguy great point.  Makes sense to not have CSS/font configuration settings for developers using the framework in the **Encore UI Styleguides**.  At least not to for a basic install.  I'll make the changes.

**Comment by CITguy** [comment]
Yeah, I tested locally and I've got no problems with the font using `@import`. Don't forget to remove the `<link>` for the font in `demo/index.html`.

**Comment by 100stacks** [comment]
screen shot 2015-10-09 at 11 39 41 am

**Comment by 100stacks** [comment]
@CITguy okay changes made :+1:

**Comment by CITguy** [comment]
LGTM

**Comment by glynnis** [comment]
LGTM

**Pull request merged**
