### PR TITLE
fix(spelling): Managed was mispelled

### PR DESCRIPTION
**Pull request by jj4th**

### CODE REVIEW

**Comment by CITguy** [comment]
@jj4th, this PR is unnecessary. I've addressed the spelling error in #871

**Comment by jj4th** [comment]
@CITguy You only changed it in one of the two files.

**Comment by CITguy** [comment]
Ah, I was unaware of the other file.

**Comment by CITguy** [comment]
but now I'm curious as to why we have the same demo code in two places...

**Comment by jj4th** [comment]
Oh nice, dependency failure.

**Comment by jj4th** [comment]
retest this please

**Comment by parlarjb** [comment]
@CITguy The duplication is a side-effect of how are docs are currently split up. We previously _only_ had the component docs, not the style guide. Now we have the question of "what should go in the style guide, what should be with the components?" Eventually they'll be combined into something more cohesive.

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
