### PR TITLE
style(rxMetadata): correct margins

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-132

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

Corrected top/bottom margin as well as simplified gutters.

### CODE REVIEW

**Comment by CITguy** [comment]
## Before

### rx-metadata
old-rx-metadata

### section
old-rx-metadata-col

**Comment by CITguy** [comment]
## After

## rx-metadata
* applies top/bottom margins for proper sibling spacing

new-rx-metadata


## section
* handles only horizontal spacing within `<rx-metadata>`
* simplified gutters
* no unintended indentation

new-rx-metadata-col1

## rx-meta
* handles vertical spacing within `<rx-metadata>`

new-rx-metadata-meta-margin

**Comment by glynnis** [comment]
:ear_of_rice: :family: :last_quarter_moon_with_face: LGTM!

This kind of careful look at margins for different components/patterns is something I hope to do more of as we audit the Framework :+1: Nice to see some of it is already getting done!

**Comment by bry4n** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM for the glorious screenshots

**Pull request merged**
