### PR TITLE
chore(navItemTarget): Use null instead of _self as default target

### PR DESCRIPTION
**Pull request by halkon**
JIRA:

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM
- [x] QE LGTM

### CODE REVIEW

**Comment by lentusignavus** [comment]
@halkon Why not self?

**Comment by halkon** [comment]
@lentusignavus from reading:
http://stackoverflow.com/questions/16837704/angularjs-normal-links-with-html5mode
and
It turns out that angular will omit taking over the html5 links when there's a `target="_self"` present.  

Interestingly enough this behavior was not exposed on other apps, but testing this change within ticketing proved to be the actual fix.

**Comment by lentusignavus** [comment]
DEV LGTM

**Comment by parlarjb** [comment]
DEV LGTM

**Pull request merged**
