### PR TITLE
style(rxapp): FRMW-334 Update Left Nav to Color 2.0

### PR DESCRIPTION
**Pull request by ssalinas24**
JIRA: https://jira.rax.io/browse/FRMW-334

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

### Before
01_before_site-branding

### After
01_after_site-branding

### Before
02_before_gray-nav-item-hover

### After
02_after_gray-nav-item-hover

### Before
02_before_nav-item-active

### After
02_after_nav-item-active

### Before
03_before_nav-level-2-and-hover

### After
03_after_nav-level-2-and-hover

### Before
03_before_nav-level-2-selected

### After
03_after_nav-level-2-selected

### Before
03_before_nav-level-2-with-children

### After
03_after_nav-level-2-with-children

### CODE REVIEW

**Comment by glynnis** [comment]
This LGTM, but @ElementE can you give this some :eyes: ?

**Comment by CITguy** [comment]
LGTM

**Comment by ElementE** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Pull request merged**
