### PR TITLE
chore(CSS): red border on invalid and dirty

### PR DESCRIPTION
**Pull request by CITguy**
JIRA

* https://jira.rax.io/browse/FRMW-147
* https://jira.rax.io/browse/FRMW-145

LGTMS

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

~~*may or may not pass midway tests. we'll see*~~

### CODE REVIEW

**Comment by CITguy** [comment]
## Chrome Screenshots

### Pristine Form - no user interaction, yet
screen shot 2015-09-18 at 5 24 43 pm

### Dirty Form, Invalid Field - after user interaction
screen shot 2015-09-18 at 5 24 51 pm

### Dirty Form, Invalid Field - after user deleted value
screen shot 2015-09-18 at 5 24 58 pm

**Comment by CITguy** [comment]
## Firefox Screenshots

### Pristine Form - no user interaction, yet

#### Before
screen shot 2015-09-18 at 5 28 05 pm

#### After
screen shot 2015-09-18 at 5 27 22 pm

### Dirty Form, Invalid Input - after user interaction

#### Before
screen shot 2015-09-18 at 5 28 15 pm

#### After
screen shot 2015-09-18 at 5 27 31 pm

### Dirty Form, Invalid Field - after user deleted value
#### Before
screen shot 2015-09-18 at 5 28 21 pm

#### After
screen shot 2015-09-18 at 5 27 39 pm

**Comment by bry4n** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Comment by CITguy** [comment]
@glynnis, @lfielder, @ElementE: Design LGTM, please.

**Comment by glynnis** [comment]
LGTM

**Pull request merged**
