### PR TITLE
docs(styleguide): Add clone icon

### LINKED ISSUE #943: Add new icon to docs
We need to add a new action link/icon to the styleguide documentation for something that's being used in the Infrastructure Management tool:

screen shot 2015-05-08 at 10 54 49 am

### PR DESCRIPTION
**Pull request by parlarjb**
Closes #943

### CODE REVIEW

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/957/gallery.html)

**Comment by megalord** [comment]
LGTM?

**Comment by glynnis** [comment]
@parlarjb This just occurred to me (and is relevant for you, @megalord since your tool uses this) -- we usually do "[icon] [verb] [noun]". So @parlarjb for doc purposes, could you add something like "Clone Container"?

@megalord I can't remember the context in your tool, but it might be worth adding the appropriate noun for wherever you're using this.

After that copy change, LGTM :+1:

**Comment by megalord** [comment]
@glynnis Yep, that change was made earlier this week.

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/957/gallery.html)

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
