### PR TITLE
refactor(framework): EO-1082 move src files

### PR DESCRIPTION
**Pull request by satyamkotakonda**
JIRA:  https://jira.rax.io/browse/EO-1082

### LGTMs
- [ ] Dev LGTM
- [ ] Dev LGTM
- [ ] Design LGTM
- [ ] QE LGTM

### CODE REVIEW

**Comment by satyamkotakonda** [comment]
@mention-bot   Sub Menu not genarated for rxSelectFilter and please help me here.

**Comment by glynnis** [comment]
@satyamkotakonda When submitting a PR, please include before and after screen shots showing what visual changes resulted from the work you did. See https://github.com/rackerlabs/encore-ui/blob/master/CONTRIBUTING.md#design-review-of-pull-requests for more detail. This makes it easier for me to conduct a design review of your PR.

Thanks!

**Comment by 100stacks** [comment]
@satyamkotakonda, in addition to the above feedback, please follow @Droogans build steps in https://github.com/rackerlabs/encore-ui/pull/1747#issuecomment-233399793 and resubmit.

**Comment by 100stacks** [comment]
@satyamkotakonda, in addition to the great feedback provided above, please see below:

0. **First** commit is **only** for moving files from one location to another. Use `git mv` for this step to move files.
0. **Second** commit should contain file edits or file removals.  Use `git rm` to remove a file.
0. To utilize the new `rxExample` construct you need a new file in a new  `elements/elementName/docs` folder called: `elementName.docs.html`   
0.  `elementName.docs.html` will looks something like this:
    ```html
    <p>
       The tooltips component provides styles to raw HTML elements and custom directive templates.
    </p>

     <rx-example name="tooltips.simple"></rx-example>
    ```

    where `tooltips.simple` above is `elementName.simple` which points to  a atomic demo and/or
    feature.
    `rxExample` looks in `elements/elementName/docs/examples` folder for `elementName.simple.html`
    and (if applicable) `elementName.simple.js` files.
0. Please see PR #1728 as an example of how to do this: https://github.com/rackerlabs/encore-ui/pull/1728/files#diff-1fbdb3a88ad53fc359b7cf5e22d3cec9  

Each demo example will be contained in a separate atomic `rxExample` construct.

**Comment by 100stacks** [comment]
@satyamkotakonda, closing this PR based on above feedback.

**Pull request closed without merging**
