### PR TITLE
test(rxSpinner): Basic visual regression

### PR DESCRIPTION
**Pull request by Droogans**

### CODE REVIEW

**Comment by Droogans** [comment]
Ah! Just realized that the spinner may be a little off each time and trigger a useless regression.

I really need to get https://github.com/rackerlabs/snappit-mocha-protractor/issues/17 added so that this isn't an issue anymore.

**Comment by Droogans** [comment]
It doesn't matter, it'll need to be much lower to trigger a regression.

```
0.17% difference in screenshot 0768x0877-By.cssSelector(".tab-content div[rx-spinner]").png
0.16% difference in screenshot 1024x0768-By.cssSelector(".tab-content div[rx-spinner]").png
0.23% difference in screenshot 0335x0568-By.cssSelector(".tab-content div[rx-spinner]").png
0.41% difference in screenshot 0568x0320-By.cssSelector(".tab-content div[rx-spinner]").png
0.19% difference in screenshot 1366x0768-By.cssSelector(".tab-content div[rx-spinner]").png
```

Currently, it's at 1%.

**Comment by Droogans** [comment]
Hey this one failed with rxNotify....paging https://github.com/rackerlabs/encore-ui/pull/1092

**Comment by megalord** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
