### PR TITLE
refactor(rxNestedElement): FRMW-400-convert to Quark service.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-400

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxMisc.rxNestedElement` to Quark service.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxNestedElement` Quark Service

### Demo Page 
This is a support function, without an example.

screen shot 2015-12-24 at 1 11 57 pm

### API Docs

screen shot 2015-12-24 at 1 12 46 pm

**Comment by glynnis** [comment]
Design LGTM

**Comment by CITguy** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Comment by 100stacks** [comment]
@parlarjb PR rebased :+1:

**Pull request merged**
