### PR TITLE
docs(cssStyleguide): Add kebab case rule for classes

### PR DESCRIPTION
**Pull request by glynnis**
JIRA: https://jira.rax.io/browse/FRMW-429

### LGTMs
- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

## After: 
screen shot 2016-03-25 at 1 54 43 pm

"Before" just doesn't include the bullet point about kebab case. Probably don't actually need a screenshot for this PR, but uh... :cake:

### CODE REVIEW

**Comment by CITguy** [comment]
LGTM

**Comment by 100stacks** [comment]
Did we decide to use `2 spaces for one level of indentation. No tabs.` for `HTML`, `CSS`, and `LESS` files?

LGTM :+1:

**Comment by CITguy** [comment]
@100stacks, good point

**Comment by ssalinas24** [comment]
LGTM

**Pull request merged**
