### PR TITLE
fix(rxAccountUsers): check account number before making API call

### PR DESCRIPTION
**Pull request by TheNando**
https://jira.rax.io/browse/FRMW-28

### CODE REVIEW

**Comment by parlarjb** [comment]
Could you please add a test here https://github.com/rackerlabs/encore-ui/blob/master/src/rxApp/rxApp.spec.js#L964 ? 

You could have a test case where `accountNumber` is not set on the `$route.current.params`, and make sure that `Encore.getAccountUsers` doesn't get called

**Comment by TheNando** [comment]
Sure thing.

**Comment by parlarjb** [comment]
LGTM

cc @halkon

**Comment by halkon** [comment]
brentrambooriginal

**Pull request merged**
