### PR TITLE
2.0.0 prep

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: n/a

The `1.x-LTS` branch has been created to handle the remaining `1.50.x` releases (including tomorrow's `1.50.1`). This PR is to bring all 2.x work back into master (effectively bringing `master` up to v2.0.0-9), so we don't have to wait on Travis/CodeShip to release tomorrow.

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM
- [x] QE LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
LGTM - did a double check over all of the changes to make sure nothing was out of place. All looks good!

**Comment by Droogans** [comment]
Nice work!

**Comment by parlarjb** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM.  Congrats on this major milestone! 🎉

**Comment by CITguy** [comment]
stewie giddy

**Comment by glynnis** [comment]
computer sunglasses

**Comment by halkon** [comment]
@klamping @rnreekez @chriscantu it only took us 2 years to get to a 2.0...

**Comment by klamping** [comment]
seems a little premature for me...

**Comment by rnreekez** [comment]
Cool.

**Comment by 100stacks** [comment]
Done! 🎉 🎉 🎉 

             ^
         _-------_  /T\      _______________
       .'  ..::. `\ |||    /                 \
      /  .::' `'` / |||    | Ship it! v2.0.0  |
     / .::' .--.=;  |||   / _________________/
     | ::' /  C ..\ |||  / /
     | :: |   \  _.)||| <_/
      \ ':|   /  \  |||
       '-, \./ \)\_0===0
          `-|   );/  |
             '--'-'' U

**Comment by chriscantu** [comment]
too soon

**Pull request merged**
