### PR TITLE
fix(style): remove unnecessary style

### PR DESCRIPTION
**Pull request by CITguy**
Demo styles inconsistent with released styles. Removing unnecessary styling from demo.less

### LGTMS
- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
### Before
before-layout-1

### After
after-layout-1

**Comment by bry4n** [comment]
LGTM

**Comment by glynnis** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM...bye `float`

**Pull request merged**
