### PR TITLE
refactor(rxVisibility): FRMW-383-convert to Quark Service.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-383

- [x] Dev LGTM
- [x] Dev LGTM

---
Refactor `rxApp.rxVisibility` to Quark Service.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxVisibility` Quark Service

### Demo Page
screen shot 2016-02-02 at 3 22 42 pm


### API Docs
screen shot 2016-02-02 at 3 41 21 pm

**Comment by CITguy** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Comment by parlarjb** [comment]
@100stacks needs a rebase, then feel free to merge

**Comment by 100stacks** [comment]
@parlarjb, sounds great thanks! :+1:

**Pull request merged**
