### PR TITLE
style(rxMetadata): correct margins

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-132

- [ ] Dev LGTM
- [ ] Dev LGTM
- [ ] Design LGTM

Corrected top/bottom margin as well as simplified gutters.

### CODE REVIEW

**Comment by CITguy** [comment]
## Before

### rx-metadata
old-rx-metadata

### section
old-rx-metadata-col

**Comment by CITguy** [comment]
## After

## rx-metadata
* applies top/bottom margins for proper sibling spacing

new-rx-metadata

## section
* handles only horizontal spacing within `<rx-metadata>`
* simplified gutters
* no unintended indentation

new-rx-metadata-col1

## rx-meta
* handles vertical spacing within `<rx-metadata>`

new-rx-metadata-meta-margin

**Comment by Droogans** [comment]
Can you push this to `rackerlabs/encore-ui` for a visual regression run?

**Comment by CITguy** [comment]
closing: submitting to `rackerlabs/encore-ui` branch for visuala regression

**Pull request closed without merging**
