### PR TITLE
chore(rxMisc): centralize rxDOMHelper

### LINKED ISSUE #734: Centralize rxDOMHelper
`rxDOMHelper` is currently defined within `rxFloatingHeader` but its functionality is used across directives.  Please move `rxDOMHelper` to its own file in a centralized location for injection by any directive.  I'd suggest using a namespace such as `encore.ui.util`.

### PR DESCRIPTION
**Pull request by CITguy**
* initialize `encore.ui.rxMisc` as a namespace for shared logic
* move `rxDOMHelper` to `rxMisc`
* Fixes #734

### CODE REVIEW

**Comment by CITguy** [comment]
Title changed to reflect "billing-only" moratorium.

**Comment by parlarjb** [comment]
How does this currently look on the demo page? Is it showing up on the left side with the other components?

Ideally, we'll at least have a README file with some documentation, and will show up with the other components, otherwise people coming to the framework won't be aware that this exists

**Comment by parlarjb** [comment]
I just pulled your branch and checked. Because there's no README, this isn't showing up in the components list on the demo page

**Comment by CITguy** [comment]
Ah, yes. That got pushed out of my short term memory. I'll hit that first thing tomorrow.

**Comment by CITguy** [comment]
Added documentation. Waiting on Travis.

**Comment by parlarjb** [comment]
LGTM

**Comment by halkon** [comment]
My only question is, whether `rxMisc` describes this best or not.  Given that this deal with UI elements I agree this staying in `encore-ui`, but if we're going to create an `rxMisc` module, just seems too open to everything, would `rxHelpers` be better? (In lieu of my original thought of `rxUtil` when I first saw it, but I'm sure that may have been already thought about).

**Comment by halkon** [comment]
Aside from the name discussion which, really it's all about the module name more than anything:

LGTM - and thank you @CITguy for doing this, I can sleep a little better at night now :grin: 
LGTM

**Pull request merged**
