### PR TITLE
style(vars): FRMW-593 Update Disabled Global Vars

### PR DESCRIPTION
**Pull request by ssalinas24**
JIRA: https://jira.rax.io/browse/FRMW-593

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

### CODE REVIEW

**Comment by glynnis** [comment]
LGTM

**Comment by glynnis** [comment]
slack-imgs-3 com

**Comment by CITguy** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM :+1:

**Pull request merged**
