### PR TITLE
fix(rxApp): Notifications width fills on nav collapse

### PR DESCRIPTION
**Pull request by MattyMcGriddle**

### CODE REVIEW

**Comment by parlarjb** [comment]
@MattyMcGriddle Thanks for submitting your first PR! Our full docs on PR submission aren't ready just yet, but in the meantime:

1. Could we please get before/after screenshots of this change
2. Is there an associated framework issue for this fix?
3. Have any of our designers (@glynnis, @lfielder, etc) signed off on this visual change?

**Comment by MattyMcGriddle** [comment]
1) Sure thing.
Before:
screen shot 2015-03-10 at 1 12 50 pm

After:
screenshot from 2015-06-04 14 58 23

2) No, but I have one in my queue for my team's issue list.
3) Not yet but they are more than welcome to before this moves forward.

**Comment by Droogans** [comment]
Rebuilding on Travis....

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

Seems like a retry is in order.

**Comment by TheNando** [comment]
Reviewed and locally test. LGTM

**Comment by parlarjb** [comment]
LGTM

**Comment by parlarjb** [comment]
I spoke with @glynnis and she was ok on this one.

**Pull request merged**
