### PR TITLE
docs(readme): Fix misspelling

### PR DESCRIPTION
**Pull request by klamping**
wheter -> whether

<3

### CODE REVIEW

**Comment by parlarjb** [comment]
double_take_eyes

**Comment by parlarjb** [comment]
LGTM

**Comment by halkon** [comment]
LGTM

**Comment by glynnis** [comment]
cat garbage

**Comment by glynnis** [comment]
cat stealth

**Comment by halkon** [comment]
chloe

**Comment by TheNando** [comment]
LGTM

**Comment by glynnis** [comment]
alison-brie-overly-attached-girlfriend-o

**Comment by halkon** [comment]
boogers

**Comment by TheNando** [comment]
Step Aside, Son

**Comment by jeremyprice** [comment]
kids-dancing-to-crazy-frog-o

**Comment by parlarjb** [comment]
cat_smoke

**Comment by halkon** [comment]
uhhhhh

**Comment by klamping** [comment]
Hey y'all how is it going just going to jump on here for a minute.

**Comment by klamping** [comment]
sorry, just trying to ruin y'all's collective productivity for the afternoon.

**Comment by jeremyprice** [comment]
post-36867-good-job-gif-hancock-will-smit-8flm

**Comment by glynnis** [comment]
cat with puppies

**Comment by klamping** [comment]
!](https://media3.giphy.com/media/EmjFkWU3KLAqs/200.gif)

**Pull request merged**
