### PR TITLE
fix(midway): add Y tolerances to rxFloatingHeader

### PR DESCRIPTION
**Pull request by CITguy**
Add ±2px tolerance for Y value comparisons to correct differing values on high resolution displays.

- [x] Dev LGTM
- [x] Dev LGTM
- [ ] QE LGTM

### CODE REVIEW

**Comment by bry4n** [comment]
LGTM

**Comment by CITguy** [comment]
Travis, Y U NO PASS

**Comment by 100stacks** [comment]
LGTM

**Comment by CITguy** [comment]
oops, didn't mean to close this, but I apparently lost my local changes >_<

**Pull request closed without merging**
