### PR TITLE
refactor(rxDOMHelper): FRMW-399-convert to Quark Service.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-399

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxMisc.rxDOMHelper` to Quark Service.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxDOMHelper` Quark Service

### Demo Page
screen shot 2016-01-11 at 10 49 11 am

### API Docs
screen shot 2016-01-11 at 9 37 45 am

**Comment by 100stacks** [comment]
**TODO:** Add `{@link quarks.service:rxDOMHelper rxDOMHelper}` to `quarks.module.js`.

**Comment by glynnis** [comment]
Design LGTM

**Comment by CITguy** [comment]
Dev LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
