### PR TITLE
fix(rxMetadata): provide correction to unbreakable data values

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-104

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM
- [x] QE LGTM

### Without word-break
screen shot 2015-08-12 at 2 27 15 pm

### With word-break
screen shot 2015-08-12 at 2 10 38 pm

### CODE REVIEW

**Comment by parlarjb** [comment]
LGTM

**Comment by Droogans** [comment]
@CITguy I happen to be working on a branch to fix some things with rxMetadata page objects.

Mind if I push it on top of this code here?

**Comment by Droogans** [comment]
LGTM

**Comment by glynnis** [comment]
LGTM

**Comment by TheNando** [comment]
LGTM

**Pull request merged**
