### PR TITLE
feat(rxFeedback): Update API endpoint and add fields to feeback

### PR DESCRIPTION
**Pull request by julianbonilla**
Updates API endpoint to `/api/encore/feedback`.  User feedback now includes sso, current page and browser agent.

### CODE REVIEW

**Comment by parlarjb** [comment]
@halkon @nickburns2006 Could you two please look at this, as TQ is the only thing currently using the API?

**Comment by halkon** [comment]
From TQ's usage there is no issue with this.  

However some of this stuff seems to be stuff that can be retrieved from `Headers` and the `X-Auth-Token`.  

But then again, if we do try to make it as "API agnostic" then no biggie

:+1:

**Comment by julianbonilla** [comment]
@halkon I like the idea of retrieving these from the headers on the API side. I'll try that.

**Comment by julianbonilla** [comment]
@halkon Moved the current page and user agent to the API side.  Now just sending the id with the feedback.

**Comment by parlarjb** [comment]
@julianbonilla is the endpoint for this currently up and running?

**Comment by halkon** [comment]
it just got merged in yesterday, we can deploy it to `staging` `preprod` if anyone is feeling... daring

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/946/gallery.html)

**Comment by parlarjb** [comment]
@julianbonilla Is the process for getting the product-specific endpoint documented anywhere? And if so, could you add a pointer to it here? Based on what we've got in this PR, teams won't know they can request their own product-specific endpoint

**Comment by parlarjb** [comment]
LGTM

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/946/gallery.html)

**Comment by chriscantu** [comment]
@julianbonilla @parlarjb Should this PR include the removing of the 'mailto' link approach?  Or should that be submitted in separate PR?  

https://github.com/rackerlabs/encore-ui/blob/master/src/rxFeedback/rxFeedback.js#L79

**Comment by julianbonilla** [comment]
@chriscantu I think we should keep `mailto` as a fallback when the API fails.

**Comment by chriscantu** [comment]
@julianbonilla Kool!

Legit

**Pull request merged**
