### PR TITLE
docs(wording): normalize to 'EncoreUI'

### LINKED ISSUE #578: Documentation: Change all instances of EncoreUI to Encore-UI
In documentation, we should stick to one format: Encore-UI over EncoreUI. Consistency, you're a cruel mistress.

### PR DESCRIPTION
**Pull request by CITguy**
* Closes #578

### CODE REVIEW

**Comment by parlarjb** [comment]
LGTM

**Comment by glynnis** [comment]
Sorry to throw a wrench in this, but is this still relevant? In all our meeting invites and various other docs I feel like I see "Encore UI" and "EncoreUI" more frequently. This is something that's worth confirming with @chriscantu I think, and if "Encore-UI" is correct we'll have a few other follow-up tasks to update other areas that aren't consistent :grin:

**Comment by parlarjb** [comment]
The "decision" on how to name it was made by me and Ernie a long time ago, with no particular reason. I'm happy for whatever.

**Comment by chriscantu** [comment]
@CITguy @glynnis @parlarjb Do we have strong convictions which one we want?  I was thinking Encore~UI but then thought it was to passé. 

Now, I am thinking EncoreUI should be the 'official' spelling only because its one less character to type. :smile:

**Comment by parlarjb** [comment]
@kobowley Final decision goes to you

**Comment by CITguy** [comment]
I'm with @parlarjb. I'm happy for whatever. I just need to know the appropriate spelling and I'll get documentation updated.

**Comment by kobowley** [comment]
EncoreUI it shall be.

**Comment by glynnis** [comment]
Sweet, glad we have a decision! :clap: :clap: :clap: :clap: 

But really, wouldn't eNc0R3~U1 be best? :trollface:

**Comment by CITguy** [comment]
I'll get the docs updated.

**Comment by CITguy** [comment]
Documentation updated with normalized "EncoreUI" naming.

**Comment by chriscantu** [comment]
LGTM

LGTM

**Pull request merged**
