### PR TITLE
FRMW-76: Split rxMultiSelect into its own directive from rxSelectFilter 

### PR DESCRIPTION
**Pull request by 100stacks**
* [x] Dev
* [x] Dev
* [x] Design

Breakout on ```rxMultiSelect``` **directive** from ```rxSelectFitler```

https://jira.rax.io/browse/FRMW-76

### CODE REVIEW

**Comment by 100stacks** [comment]
screen shot 2015-09-16 at 2 51 57 pm

**Comment by CITguy** [comment]
LGTM

**Comment by bry4n** [comment]
LGTM

**Comment by CITguy** [comment]
@glynnis, or @lfielder: design review, please

**Comment by CITguy** [comment]
Design Review, please.

/cc @glynnis, @lfielder, @ElementE

**Comment by glynnis** [comment]
Checked this out locally and it looks like the checkbox icons aren't working the way they should.

### This PR
screen shot 2015-09-23 at 2 29 30 pm

### http://rackerlabs.github.io/encore-ui/#/components/rxSelectFilter
screen shot 2015-09-23 at 2 30 10 pm

It's unclear to me whether the problem is something with my environment or something with the PR itself. @CITguy any ideas?

**Comment by CITguy** [comment]
@glynnis, I've checked it out locally with no problem. 

screen shot 2015-09-23 at 3 00 38 pm

Are you getting any errors in the console? Maybe `bower install`...

**Comment by glynnis** [comment]
I ran a `bower install` so not sure what the issue is, but that was the only thing I saw that seemed off, so LGTM :+1:

**Pull request merged**
