### PR TITLE
fix(rxAccountUsers): Fix ever increasing user calls

### LINKED ISSUE #1156: rxAccountUsers does not properly release watcher
When the directive rxAccountUsers unloads, it does not properly unregister its rootScope watcher.  This results in stacking calls to the encore account users service.

The call in question is on line https://github.com/rackerlabs/encore-ui/blob/master/src/rxApp/rxApp.js#L503

### PR DESCRIPTION
**Pull request by jj4th**
This is the PR to fix #1156 

- [X] Dev LGTM
- [x] Dev LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
@jj4th: can you update the tests for this change?

**Comment by jj4th** [comment]
There are no tests to update for this change :)

**Comment by CITguy** [comment]
Sorry, I meant update via adding a test for this.

**Comment by jj4th** [comment]
Added a unit test :smile_cat:

**Comment by parlarjb** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
