### PR TITLE
test(exerciese): Remove deprecated cssSelector option

### PR DESCRIPTION
**Pull request by Droogans**
JIRA: https://jira.rax.io/browse/FRMW-211

### LGTMs
- [x] Dev LGTM
- [x] Dev/QE LGTM

FRMW-211 #in-review

BREAKING CHANGE: You will need to refer to the component under test
using the `instance` option, which should be a page object that you
instantiate yourself, and hand into the exercise.

### CODE REVIEW

**Comment by Droogans** [comment]
Wiki Updated: https://github.com/rackerlabs/encore-ui/wiki/2.0-Migration-Guide#removed-cssselector

**Comment by CITguy** [comment]
LGTM

**Comment by 100stacks** [comment]
@Droogans @CITguy, what do you all think about adding a `DEPRECATION` label for PRs such as these?

LGTM :+1:

**Comment by CITguy** [comment]
@100stacks, I think that's what the `2.x Release` label is for

**Pull request merged**
