### PR TITLE
refactor(Forms): EO-1092 refactor help text forms

### PR DESCRIPTION
**Pull request by khaziwallis**
JIRA: https://jira.rax.io/browse/EO-1092

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM
- ~~[ ] QE LGTM~~ (no change to functional javascript)
- ~~[ ] Design LGTM~~ (no change to copy)

Application Page
------------
screen shot 2016-08-25 at 4 35 22 pm

API Page
------------
screen shot 2016-08-25 at 4 35 49 pm

Note: the proper redirection to API page was taken care in previous PR.

### CODE REVIEW

**Comment by KalpeshBhandari** [comment]
Dev LGTM

**Comment by 100stacks** [comment]
LGTM

**Comment by CITguy** [comment]
@khaziwallis: please rebase

**Comment by 100stacks** [comment]
@khaziwallis: please rebase this PR.

It can merged once conflicts are resolved and it passes Travis/Codeship CI builds.

**Pull request merged**
