### PR TITLE
refactor(rxDatePicker): FRMW-762 migrate to Forms Element

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-762

### LGTMs
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxDatePicker` to Form Element.   No more `Atoms` or `Molecules`! 🎉

### CODE REVIEW

**Comment by 100stacks** [comment]
## `Date Picker` Form Element

### `Date Picker` Section on Demo Page
encoreui 2016-05-12 11-27-48

### API Docs
rxdatepicker 2016-05-12 11-29-00

### Complete Form Element Demo Page
encoreui 2016-05-12 11-26-51

**Comment by parlarjb** [comment]
LGTM

**Comment by glynnis** [comment]
Design LGTM

**Comment by CITguy** [comment]
Woo! No more Atoms or Molecules!

**Pull request merged**
