### PR TITLE
docs(buttons): Add new Billing icons to buttons/links docs

### PR DESCRIPTION
**Pull request by glynnis**
See https://jira.rax.io/browse/UXENCORE-214

Before:
screen shot 2015-03-19 at 3 02 18 pm

After:
screen shot 2015-03-19 at 3 01 58 pm

### CODE REVIEW

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/853/gallery.html)

**Comment by velveteer** [comment]
Aww it's so special! :snowflake:

**Comment by parlarjb** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
