### PR TITLE
docs(Overview): move 'Other Links' to Overview

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-109

### Before
screen shot 2015-08-20 at 3 08 13 pm

### After
screen shot 2015-08-20 at 5 06 31 pm

- [x] Dev LGTM
- [ ] Dev LGTM
- [x] Design LGTM

### CODE REVIEW

**Comment by glynnis** [comment]
@CITguy As part of this PR can you also remove the "EncoreUI" blue stripe, the "JS Docs" and "Test Docs" link so the nav more closely matches the top level of the nav here? https://projects.invisionapp.com/d/main#/console/3774467/82232843/preview

**Comment by CITguy** [comment]
@glynnis: updated code and "After" screenshot

**Comment by parlarjb** [comment]
LGTM

**Comment by glynnis** [comment]
LGTM

**Comment by parlarjb** [comment]
Not waiting for a second dev sign-off on this one

**Pull request merged**
