### PR TITLE
docs(forms): Fix design pattern for manual saving.

### LINKED ISSUE #907: Create a "save" feature
An emerging need in Encore applications is the ability to manually or auto-save progress while completing forms.

We need a visual/interactive pattern for this, including decisions around:
- visual treatment
- placement
- interactive design
- whether manual vs. auto is an option

Also needs to be added as a component or reusable style in the framework. @megalord has some work already put in on this in an application, but not at the Framework level.

cc @megalord @ElementE @parlarjb

### PR DESCRIPTION
**Pull request by megalord**
- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM
- [x] QE LGTM

[Invision](https://projects.invisionapp.com/d/main#/console/3750442/81735376/preview)
The manual save pattern was redone awhile back, but I didn't get around to updating the docs until now (sorry :smile: ).  Fixes #907 

screen shot 2015-07-08 at 10 45 40 am
screen shot 2015-07-08 at 10 46 36 am
screen shot 2015-07-08 at 10 46 57 am

### CODE REVIEW

**Comment by parlarjb** [comment]
LGTM

**Comment by glynnis** [comment]
@megalord it looks like the `.xs` styles on the button aren't getting properly applied. I think they're getting overwritten by the header class font size, which should be fixed before merging.

**Comment by megalord** [comment]
Thanks @glynnis!  Updated screenshot:
screen shot 2015-07-09 at 3 22 02 pm

**Comment by Droogans** [comment]
Let me push up some screenshots on top of this real quick.

**Comment by Droogans** [comment]
@megalord **This PR has been rebased. I force pushed to it.**

**Comment by CITguy** [comment]
LGTM

**Comment by Droogans** [comment]
Rebuilding since the screenshots got merged in another PR. Let's see the visual diff now that there aren't 46 of them.

**Comment by glynnis** [comment]
LGTM

**Pull request merged**
