### PR TITLE
refactor(commacleanup): FRMW-553 remove unnecessary commas

### PR DESCRIPTION
**Pull request by jgonz0010**
Got rid of the extra commas associated with arrays and the commas at the end of the arrays. Check out FRMW-553 for more info. Link Below.

https://jira.rax.io/browse/FRMW-553

- [x] Dev LGTM
- [x] Dev LGTM

### CODE REVIEW

**Comment by Droogans** [comment]
I'm surprised @parlarjb was OK with this being a story at all in the first place. He really pushes for extraneous trailing commas, and I agree with him (although I've yet to make a solid habit out of it yet).

**Comment by jgonz0010** [comment]
To be fair he has probably not seen it yet. You are not the first to mention it though. With that being said, I don't think putting them in or keeping them out is an issue anymore. Given that even IE has made changes so that commas at the end of the arrays are ignored. :-)

**Comment by 100stacks** [comment]
I'm for removing the trailing comma `,` -- if we keep them as a matter of preference, we should annotate this in our [JavaScript Styleguide](http://rackerlabs.github.io/encore-ui/#/guides/js-styleguide).
 
LGTM :+1:

**Comment by CITguy** [comment]
Though we don't support IE, I'm still for removing the trailing commas. :+1:

**Comment by CITguy** [comment]
LGTM

@parlarjb, do you have anything you'd like to add?

**Comment by parlarjb** [comment]
I'll let Raymond Hettinger (one of the smartest people I've ever seen speak) show why trailing commas are the preferred way in the Python community 

http://stackoverflow.com/a/11597911

(Plus it makes it easier for people to add to the list)

**Comment by CITguy** [comment]
Ok, @parlarjb. You've convinced me. Given that trailing commas are not breaking ES5 spec and that we don't officially support IE, I'm going to close this PR.

**Comment by CITguy** [comment]
Sorry @jgonz0010. :(

**Comment by jgonz0010** [comment]
it's all good! I'll remove the trailing commas rule from my analysis tool.

**Pull request closed without merging**
