### PR TITLE
chore(componentTemplate): update for standard component ngdocs

### PR DESCRIPTION
**Pull request by CITguy**
* add quick blurb to define basic component ngdocs overview page
* add link to component ngdocs overview page in README

### LGTMs
- [x] Dev LGTM
- [x] Dev LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
Provides the following (via screenshots)

*API Documentation* link automatically added to generated README
screen shot 2015-09-09 at 4 23 01 pm

*Basic API overview page for `rxFooBar` component*
screen shot 2015-09-09 at 4 23 12 pm

**Comment by bry4n** [comment]
This is useful :+1: LGTM

**Comment by CITguy** [comment]
Well, it's useful for new components going forward, but we still need to implement this pattern among the rest of the components.

**Comment by CITguy** [comment]
@parlarjb, any comments?

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
