### PR TITLE
refactor(lists): Put Lists into Atoms

### PR DESCRIPTION
**Pull request by parlarjb**
https://jira.rax.io/browse/FRMW-277

 - [x] Dev LGTM
 - [x] Dev LGTM
 - [x] Design LGTM

screen shot 2016-02-24 at 4 36 22 pm

### CODE REVIEW

**Comment by glynnis** [comment]
@parlarjb A lot of the styling/visual changes from the mock-up/JIRA story aren't represented in the work here. Is that being tackled as part of a separate effort?

**Comment by parlarjb** [comment]
My understanding was that these stories were just about moving things around, but I could be completely wrong. @CITguy do you have a better understanding?

**Comment by CITguy** [comment]
@glynnis, @parlarjb: See https://github.com/rackerlabs/encore-ui/pull/1581#issuecomment-189344049

TL;DR - Arranging information can be done now. Styling may have to be done later.

**Comment by glynnis** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM, @parlarjb please rebase

**Pull request merged**
