### PR TITLE
test(ci): Split firefox e2e testing to travis

### PR DESCRIPTION
**Pull request by Droogans**
JIRA: https://jira.rax.io/browse/FRMW-84

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM

This will also move all chrome-based tests to codeship, which offers
an opportunity to do console checks for any javascript errors when
running e2e tests. Protractor offers a plugin for failing a suite
whenever a javascript error is detected in the console, no matter
when it occurred. So now all chrome tests silently watch for javascript
errors during all phases of e2e testing, replacing (and improving upon)
the phantomjs:checkAllModules grunt task that did this previously.

Closes https://jira.rax.io/browse/FRMW-84

### CODE REVIEW

**Comment by Droogans** [comment]
I forgot to delete the phantomjs source task, I just deleted the part where it integrated into the `grunt test` task.

**Comment by Droogans** [comment]
Marking as urgent since this introduces a new `protractor.chrome.conf.js` file that the codeship build scripts expect to exist. Other PRs will fail on codeship until this gets merged!

**Comment by 100stacks** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM - we'll wait for #1737 tests and then merge this in

**Pull request merged**
