### PR TITLE
refactor(rxBulkSelectController): FRMW-703-conver to Quark Controller

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-703

- [x] Dev LGTM
- [x] Dev LGTM

---
Refactor `rxBulkSelect.rxBulkSelectController` to Quark Controller.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxBulkSelectController` Quark Controller

### Demo Page
screen shot 2016-02-17 at 2 19 35 pm

### API Docs
screen shot 2016-02-17 at 2 22 43 pm

**Comment by parlarjb** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM

**Comment by 100stacks** [comment]
### Hopefully that should be it for this round of `Quarks`!

gotham-season-2

**Pull request merged**
