### PR TITLE
docs(rxAge): FRMW-296 Update rxAge

### PR DESCRIPTION
**Pull request by ssalinas24**
JIRA: https://jira.rax.io/browse/FRMW-296

- [x] Dev LGTM
- [x] Dev LGTM

### CODE REVIEW

**Comment by ssalinas24** [comment]
@CITguy Would the third example on the following page also need to change?
http://localhost:9001/ngdocs/index.html#/api/rxAge/

**Comment by CITguy** [comment]
No, but the midway test for the last demo will need updated.

**Comment by ssalinas24** [comment]
@CITguy My second commit contains the update to the midway, and it looks like everything passed now.

**Comment by CITguy** [comment]
LGTM

@ssalinas24, please squash in preparation for merge.

**Comment by ssalinas24** [comment]
@CITguy Thank you for the feedback and review. I have completed the squash.

**Comment by bry4n** [comment]
LGTM

**Pull request merged**
