### PR TITLE
fix(css): rx-app-search icon

### PR DESCRIPTION
**Pull request by CITguy**
* In regards to #782
* Fix `position: absolute;` attachment

### CODE REVIEW

**Comment by Droogans** [comment]
@velveteer has his setup all ready for pulling in changes in encore-ui to reflect his local build, and seeing how this is his problem specifically, should probably be merged by him.

**Comment by velveteer** [comment]
LGTM. This fixes the issue locally. My only concern is are we ok with changing `fieldset` behavior across the entire framework?

**Comment by parlarjb** [comment]
For my own edification, this fix is taking advantage of this? http://css-tricks.com/absolute-positioning-inside-relative-positioning/

**Comment by CITguy** [comment]
@parlarjb: yes, exactly

**Comment by CITguy** [comment]
@velveteer: this change only affects fieldsets within the `.rx-app-search` scope, so it's not globally modifying `fieldset` behavior.

**Comment by velveteer** [comment]
@CITguy Ah I see that now after viewing the full file. Then this definitely LGTM.

**Comment by CITguy** [comment]
@parlarjb, @Droogans, who should merge this?

**Comment by Droogans** [comment]
I nominate @glynnis...she's a neutral third party (who, unlike me, actually understands the full ramifications of this kind of a change).

**Comment by parlarjb** [comment]
Let's merge this in as soon as the framework freeze is over

**Comment by CITguy** [comment]
This is billing-specific. Will that affect when it's merged?

**Comment by glynnis** [comment]
LGTM :+1: Interestingly enough, no other search boxes in the nav are using `<fieldset>` around `<input>`s within their `<form>`s. Should that someday be the case, though, @CITguy is correct -- this is correctly scoped and shouldn't affect other fields around Encore.

:dancer: :dancer: :dancer:

**Pull request merged**
