### PR TITLE
fix(contributing): update rebase instructions

### PR DESCRIPTION
**Pull request by TheNando**
Update rebase instructions to account for merge conflicts

### CODE REVIEW

**Comment by Droogans** [comment]
:+1: for roman numeral sub-lists. Didn't know that was a thing.

**Comment by CITguy** [comment]
LGTM

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/937/gallery.html)

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/937/gallery.html)

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/937/gallery.html)

**Pull request merged**
