### PR TITLE
refactor(rxOptionTable): remove rxOptionTable.unselectAll

### PR DESCRIPTION
**Pull request by kevincareer427**
JIRA: https://jira.rax.io/browse/FRMW-912

### LGTMs
- [x] Dev LGTM
- [x] Dev LGTM

### CODE REVIEW

**Comment by parlarjb** [comment]
LGTM

**Comment by kevincareer427** [comment]
Migration Guide has been updated: 
https://github.com/rackerlabs/encore-ui/wiki/2.0-Migration-Guide#removed-unselectall-function

**Comment by CITguy** [comment]
Added "Do Not Merge" because I want to make sure that `deselectAll()` still carries over when synchronizing 2.x with 1.x

**Comment by kevincareer427** [comment]
@CITguy sure

**Comment by CITguy** [comment]
@kevincareer427: please rebase

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
