### PR TITLE
refactor(quarks): FRMW-407 rxPageTracking FRMW-408 rxPaginateUtils.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-407 (`rxPaginate.PageTracking`)
JIRA: https://jira.rax.io/browse/FRMW-408 (`rxPaginate.rxPaginateUtils`) 

- [x] Dev LGTM
- [x] Dev LGTM

---
Refactor `rxPaginate.PageTracking` and `rxPaginate.rxPaginateUtils` to Quark Services.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `PageTracking` Quark Service

### Demo Page
screen shot 2016-02-08 at 2 48 16 pm

### API Docs
screen shot 2016-02-08 at 2 48 50 pm

**Comment by 100stacks** [comment]
## `rxPaginateUtils` Quark Service

### Demo Page
screen shot 2016-02-08 at 2 15 53 pm


### API Docs
screen shot 2016-02-08 at 2 16 15 pm

**Comment by CITguy** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
