### PR TITLE
refactor(rxFormUtils): FRMW-396-convert to Quark Service.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-396

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxForm.rxFormUtils` to Quark Service.

### CODE REVIEW

**Comment by 100stacks** [comment]
**TODO:**  Add `{@link quarks.service:rxFormUtils rxFormUtils}` to `quarks.module.js`.

**Comment by 100stacks** [comment]
## `rxFormUtils` Quark Service

### Demo Page
screen shot 2016-01-08 at 1 50 51 pm

### API Docs
screen shot 2016-01-08 at 1 51 41 pm

**Comment by CITguy** [comment]
LGTM

**Comment by glynnis** [comment]
Design LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
