### PR TITLE
fix(UnauthorizedInterceptor): Include search in return url.

### PR DESCRIPTION
**Pull request by megalord**
JIRA: N/A

This wasn't caught in the unit tests because they stub the `redirectPath()` method to return exactly what they want it to.

### LGTMs
- [ ] Dev LGTM
- [ ] Dev+Vidyo LGTM
- [ ] Design LGTM
- [ ] QE LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
@megalord: could you update the tests to account for this change?

**Comment by CITguy** [comment]
Due to inactivity, I'm closing this PR.

@megalord, please resubmit with updated tests if you want to contribute this functionality.

**Comment by megalord** [comment]
Ah sorry, forgot about this.  Yeah I'd like to, but I won't have time soon, so I figure it'd be best to make an issue in the meantime to help remember.  Do you prefer Jira or GitHub?

**Comment by CITguy** [comment]
@megalord: JIRA would be best, but either will work.

**Comment by megalord** [comment]
Sounds good, filed [here](https://jira.rax.io/browse/FRMW-1211)

**Pull request closed without merging**
