### PR TITLE
docs(rxRadio): Page objects to jsdoc3

### PR DESCRIPTION
**Pull request by Droogans**
### LGTMs
- [x] Dev LGTM
- [x] QE LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
@Droogans, can you do a push to trigger a Travis build? For some reason, the Travis job for this PR has disappeared. (Yes, I know it shouldn't matter considering it's documentation, but I'd sleep better knowing that Travis agrees.)

**Comment by Droogans** [comment]
I'll close/reopen. So much faster.

**Comment by CITguy** [comment]
Duh, why didn't I think of that?

**Comment by CITguy** [comment]
LGTM

**Comment by jj4th** [comment]
QE-LGTM

**Pull request merged**
