### PR TITLE
fix(styles): remove code block style

### PR DESCRIPTION
**Pull request by TheNando**
Remove code styles until they can get proper design attention.

https://github.com/rackerlabs/encore-ui/issues/940

### CODE REVIEW

**Comment by CITguy** [comment]
Are all styles in `responsiveLayout.less` for demo purposes?

**Comment by TheNando** [comment]
Yes. We could move it all to the demo folder, but then the user wouldn't see all the classes referenced in the markup. If this is acceptable, it's ready to push up.

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/941/gallery.html)

**Comment by CITguy** [comment]
I see what you're saying. Though the remaining styles are within class selectors, I'd feel more comfortable having them namespaced within a class used for demonstration purposes (`.layout-demo { ... }` or similar). The added class names *shouldn't* affect developers' source code, but there's still a possibility that they'd bring up conflicts. @glynnis @parlarjb, comments?

**Comment by TheNando** [comment]
Good point. I'll wrap it up.

**Comment by CITguy** [comment]
Having said that, I would give a soft *lgtm* on this.

**Comment by CITguy** [comment]
With namespaced styles, LGTM.

**Comment by TheNando** [comment]
Squashed and ready to merge.

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/941/gallery.html)

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
