### PR TITLE
docs(Tables): document static column widths

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-1144

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM
- [x] Design LGTM
- [x] QE LGTM (no change to test functionality, just modified CSS selectors)

### Summary

* add "Known Bugs and Workarounds" section to Table documentation
* update table demos with pagination
* update table demos with floating headers
* rename an example LESS file to adhere to naming convention

### CODE REVIEW

**Comment by CITguy** [comment]
The main issue is with navigation of paginated data.

### Before
*Notice how the columns change width as we navigate the pages.*
table-ui-pagination-broken

### After
*Chrome*
table-ui-pagination-fixed-chrome

*Firefox*
table-ui-pagination-fixed-firefox

**Comment by parlarjb** [comment]
Vidyo LGTM

**Comment by halkon** [comment]
LGTM

**Comment by ElementE** [comment]
Design LGTM

**Pull request merged**
