### PR TITLE
fix(css): bump size of field labels

### PR DESCRIPTION
**Pull request by CITguy**
* increase field labels by 10px for slightly larger values

### CODE REVIEW

**Comment by CITguy** [comment]
Turns this:
screen shot 2015-01-20 at 3 10 37 pm


Into this (moar spacing between label and input):
screen shot 2015-01-21 at 11 42 37 am

**Comment by CITguy** [comment]
Please see comment at [encore-cloud-ui#417](https://github.com/rackerlabs/encore-cloud-ui/pull/417#issuecomment-70900042) in reference to label width.

**Comment by glynnis** [comment]
LGTM :rabbit: :rabbit2: :radio:

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
