### PR TITLE
Frmw-1352 - notification

### PR DESCRIPTION
**Pull request by keithcruz**
JIRA: https://jira.rax.io/browse/FRMW-1352

### LGTMs
- [x] Dev LGTM
- [ ] Dev+Vidyo LGTM
- [x] QE LGTM

### CODE REVIEW

**Comment by jj4th** [comment]
rxNotify tests appear to be passing in this branch so.  QE-LGTM.

**Comment by halkon** [comment]
@keithcruz I think I remember doing this work, and I'd like to perhaps to a vidyo review of this monday? What do you think?

I want to be really careful, as the idea before was that we would be able to add HTML elements into the notification bar.

**Comment by halkon** [comment]
I am really scared specifically about having changed the unit test from `.eq(1)` vs `.eq(0)`

**Comment by keithcruz** [comment]
@halkon That sounds good, I'll also look further into it in the mean time.

**Pull request merged**
