### PR TITLE
fix(css): rxMultiSelect support

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-793

### LGTMs
- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM
- ~~[x] QE LGTM~~ No change to tests

### CODE REVIEW

**Comment by CITguy** [comment]
### BEFORE
screen shot 2016-03-28 at 4 17 33 pm


### AFTER
screen shot 2016-03-28 at 4 20 19 pm

**Comment by 100stacks** [comment]
LGTM

**Comment by bry4n** [comment]
CSS change and screenshot LGTM

**Comment by ssalinas24** [comment]
LGTM

**Pull request merged**
