### PR TITLE
chore(colors): squash - refactor markup/styles

### PR DESCRIPTION
**Pull request by CITguy**
Suggested refactor to Glynnis' color updates.

Improvements:
* simpler markdown
* better organization of LESS
* adds "Roboto Mono" font family for monospace needs

_resubmitted: git branch issues_

### CODE REVIEW

**Comment by CITguy** [comment]
screen shot 2015-10-27 at 6 57 50 pm
screen shot 2015-10-27 at 6 57 59 pm
screen shot 2015-10-27 at 6 58 05 pm

**Comment by bry4n** [comment]
LGTM

**Comment by CITguy** [comment]
lol, no LGTM's needed on this one. It's a PR to merge into Glyniss' PR

**Comment by glynnis** [comment]
This is awesome -- thanks!

**Pull request merged**
