### PR TITLE
refactor(rxStatusColumnIcons): FRMW-417-convert to Quark object.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-417

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxStatusColumn.rxStatusColumnIcons` to Quark object.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxStatusColumnIcons` Quark Object

### Demo Page
screen shot 2016-01-15 at 1 58 55 pm

### API Docs
screen shot 2016-01-15 at 1 58 42 pm

**Comment by glynnis** [comment]
Does this one need a demo to show the visuals of mappings, or is that handled somewhere else?

**Comment by 100stacks** [comment]
@glynnis, I could point users to :point_right: http://rackerlabs.github.io/encore-ui/#/components/rxStatusColumn or do you think I should show them the icon mappings on the Quark page?

**Comment by glynnis** [comment]
@100stacks If rx-example is used, I don't see any harm in including it on the Quark page. Otherwise, I think a link would suffice.

**Comment by 100stacks** [comment]
@glynnis, updated the `rxStatusColumnIcons` Quark demo page along with the screenshot https://github.com/rackerlabs/encore-ui/pull/1499#issuecomment-172078741. :+1:

**Comment by glynnis** [comment]
Design LGTM

**Comment by CITguy** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
