### PR TITLE
style(rxStatusColumn): Update status column colors to 2.0

### PR DESCRIPTION
**Pull request by glynnis**
https://jira.rax.io/browse/FRMW-337

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

### Before
screen shot 2015-12-16 at 5 11 47 pm

### After
screen shot 2015-12-16 at 5 11 40 pm

### CODE REVIEW

**Comment by glynnis** [comment]
Made these match rxNotify (https://github.com/rackerlabs/encore-ui/pull/1423) as much as possible color-wise.

**Comment by CITguy** [comment]
LGTM

**Comment by glynnis** [comment]
Created a separate story for making the icons for rxStatusColumn better match those of rxNotify: https://jira.rax.io/browse/FRMW-556

**Comment by ssalinas24** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Pull request merged**
