### PR TITLE
refactor(table): FRMW-106 - Update design pattern for table filtering

### PR DESCRIPTION
**Pull request by bry4n**
JIRA: https://jira.rax.io/browse/FRMW-106

* [ ] Dev LGTM
* [ ] Dev LGTM

Screenshot:
screen shot 2015-09-09 at 4 23 32 pm

### CODE REVIEW

**Comment by Droogans** [comment]
@bry4n can you please push this up to `rackerlabs/encore-ui` for a visual regression check?

**Comment by bry4n** [comment]
@Droogans yes. I'll make another PR

**Comment by CITguy** [comment]
@bry4n, hold off on that new PR. There are some things that need to be addressed with the JIRA story.

**Comment by bry4n** [comment]
@CITguy ah i just created a new PR. https://github.com/rackerlabs/encore-ui/pull/1191

**Pull request closed without merging**
