### PR TITLE
style(less): FRMW-98-Standardize LESS Indentation

### PR DESCRIPTION
**Pull request by 100stacks**
Standardize LESS Indentation to 4 spaces per tab: https://jira.rax.io/browse/FRMW-98

* [x] Dev - LGTM
* [x] Dev - LGTM

### CODE REVIEW

**Comment by bry4n** [comment]
Hmm. the `layout.less` looks outdated to me. Can you make sure this branch has latest master?


See `layout.less` changes: https://github.com/rackerlabs/encore-ui/commit/3bae06b9ca7bb564b69e81516c5f36c355b9cfef

**Comment by CITguy** [comment]
@100stacks, please rebase this PR

**Comment by 100stacks** [comment]
@CITguy okay will do.  @bry4n definitely possible with hitting all these files at once.

**Comment by 100stacks** [comment]
@CITguy @bry4n I rebased my changes....but it do not any *continuous-integration/travis-ci* status reports/updates.  Any suggestions?

**Comment by CITguy** [comment]
LGTM

**Comment by 100stacks** [comment]
Thanks @CITguy  and @bry4n for the assist!  I plan to update the Encore documentation with my lessons learned for others.

**Comment by CITguy** [comment]
Removed LGTM, for now. I'll be submitting a PR to your branch to include some missed updates.

**Comment by CITguy** [comment]
LGTM

**Comment by bry4n** [comment]
LGTM

**Pull request merged**
