### PR TITLE
refactor(rxForm): remove legacy code

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-811

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM
- [x] QE LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
2.0 migration guide updated: https://github.com/rackerlabs/encore-ui/wiki/2.0-Migration-Guide#changes-to-rxform

**Comment by parlarjb** [comment]
LGTM

How awesome did it feel to submit this PR?

**Comment by CITguy** [comment]
@parlarjb, it felt damn good

**Comment by 100stacks** [comment]
LGTM

**Comment by CITguy** [comment]
celebrate

**Pull request merged**
