### PR TITLE
Really remove bootstrap

### PR DESCRIPTION
**Pull request by halkon**
JIRA:

### LGTMs
- [ ] Dev LGTM
- [ ] QE LGTM

### CODE REVIEW

**Comment by jj4th** [comment]
@cathysiller does this depend on #2016 ?  Seems to be a typeahead issue.

**Comment by halkon** [comment]
@jj4th yes this depends on the work for #2016 I just happened to get ahead of myself. 

And nice recognizing who the author of this was 😛

**Comment by jj4th** [comment]
@halkon lol, well, Cathy has been doing a lot of "remove bootstrap" PRs lately, I just kind of assumed.  Sorry @cathysiller !

**Comment by halkon** [comment]
Temporarily rebased this on top of #2016

**Comment by jj4th** [comment]
@halkon can you re-rebase this on top of #2016 or just merge #2016... this branch has the test file problems from #2016

**Comment by jj4th** [comment]
@halkon I'm going to go ahead and fix this branch.

**Pull request merged**
