### PR TITLE
chore(grunt): stop deploying to cdn

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-968

### LGTMs
- [x] Dev LGTM
- [x] Dev/Vidyo LGTM

### CODE REVIEW

**Comment by parlarjb** [comment]
LGTM (As long as you remove the area of docs that we talked about in #framework)

**Comment by Droogans** [comment]
Any wiki updates related to this? Might make it part of the release notes so people know to stop looking at the cdn for updates (or just clear it all out and see who complains).

**Comment by 100stacks** [comment]
@CITguy, I recall we talked about this + it's on the [Road Map](https://github.com/rackerlabs/encore-ui/wiki/Road-Map#2x-200---230). 😉 

LGTM

**Comment by CITguy** [comment]
@Droogans: sections of the guides have been removed regarding CDN usage, but I'll make sure to include a note in the release notes.

**Comment by CITguy** [comment]
@Droogans: draft for release notes have been updated with note about CDN

**Pull request merged**
