### PR TITLE
refactor(rxFeedbackSvc): FRMW-394-covert to Quark Service.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-394

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxFeedback.rxFeedbackSvc` to Quark Service.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxFeedbackSvc` Quark Service

### Demo Page
screen shot 2016-01-07 at 11 54 20 am

### API Docs
screen shot 2016-01-07 at 11 55 29 am

**Comment by 100stacks** [comment]
**Note:** Need to add `rxFeedbackSvc` link to `quarks.module.js`.

**Comment by glynnis** [comment]
Design LGTM

**Comment by CITguy** [comment]
You need to modify line 8 of `rxFeedbackSvc.spec.js`.

**Comment by 100stacks** [comment]
@CITguy good catch :white_check_mark:

**Comment by CITguy** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
