### PR TITLE
chore(rxLocalStorage): FRMW-493-monolithic decomposition

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-493

- [x] Dev LGTM
- [x] Dev LGTM

---
`rxLocalStorage` monolithic decomposition.

### CODE REVIEW

**Comment by CITguy** [comment]
`src/rxLocalStorage/scripts/rxLocalStorage.js` should be named `LocalStorage.js` to reflect the service name.
`src/rxLocalStorage/scripts/rxLocalStorage.spec.js` should be named `LocalStorage.spec.js` to reflect that it is specs for the `LocalStorage` service.

**Comment by 100stacks** [comment]
@CITguy changes made :+1:

**Comment by CITguy** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
