### PR TITLE
docs(rxButton): FRMW-166-Migrate rxButton to API docs.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-166
- [x] Dev LGTM
- [x] Dev LGTM

Migrate `rxButton` to API documentation

### CODE REVIEW

**Comment by 100stacks** [comment]
screen shot 2015-09-24 at 5 20 05 pm

**Comment by 100stacks** [comment]
screen shot 2015-09-24 at 5 20 54 pm

**Comment by bry4n** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
