### PR TITLE
refactor(rxSpinner): Move components/rxSpinner to elements/rxSpinners

### PR DESCRIPTION
**Pull request by manojdas2212**
JIRA:

### LGTMs
- [ ] Dev LGTM
- [ ] Dev+Vidyo LGTM
- [ ] Design LGTM
- [ ] QE LGTM

### CODE REVIEW

**Comment by 100stacks** [comment]
@manojdas2212, as @Droogans mentioned in https://github.com/rackerlabs/encore-ui/pull/1743#issuecomment-233338905 you will have to close this PR and open a new PR with a branch off `master` to trigger the CI process.

**Comment by Droogans** [comment]
@manojdas2212 we can't run tests from pull requests that come from forks (this pull request is coming from a fork of encore-ui).

We apologize for the inconvenience. Can you run the following commands in the root directory where you are running encore-ui and try again and let us know if you have an error occur somewhere?

```
git remote add upstream git@github.com:rackerlabs/encore-ui.git
git checkout EO-1091_Framework_refractor_Spinner
git push upstream EO-1091_Framework_refractor_Spinner
```

That should then be prompted to open a pull request in the github user interface, as you might do normally.

**Comment by 100stacks** [comment]
@manojdas2212, please follow the feedback @glynnis provided in https://github.com/rackerlabs/encore-ui/pull/1743#issuecomment-23337024.

**Comment by 100stacks** [comment]
@manojdas2212, in addition to the great feedback provided above, please see below:

0. **First** commit is **only** for moving files from one location to another. Use `git mv` for this step to move files.
0. **Second** commit should contain file edits or file removals.  Use `git rm` to remove a file.
0. To utilize the new `rxExample` construct you need a new file in a new  `elements/elementName/docs` folder called: `elementName.docs.html`   
0.  `elementName.docs.html` will looks something like this:
    ```html
    <p>
       The tooltips component provides styles to raw HTML elements and custom directive templates.
    </p>

     <rx-example name="tooltips.simple"></rx-example>
    ```

    where `tooltips.simple` above is `elementName.simple` which points to  an atomic demo and/or
    feature.
    `rxExample` looks in `elements/elementName/docs/examples` folder for `elementName.simple.html`
    and (if applicable) `elementName.simple.js` files.
0. Please see PR #1728 as an example of how to do this: https://github.com/rackerlabs/encore-ui/pull/1728/files#diff-1fbdb3a88ad53fc359b7cf5e22d3cec9  

Each demo example will be contained in a separate atomic `rxExample` construct.

**Comment by manojdas2212** [comment]
@Droogans @100stacks i am getting permission issue by running the following commands..

git remote add upstream git@github.com:rackerlabs/encore-ui.git
git checkout EO-1091_Framework_refractor_Spinner
git push upstream EO-1091_Framework_refractor_Spinner

Please see the attached screen short

screen shot 2016-07-19 at 4 37 16 pm

**Pull request closed without merging**
