### PR TITLE
refactor(page_objects): FRMW-742 remove deprecated and aliased methods

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-742

### LGTMs
- [x] Dev LGTM
- [ ] Dev+Vidyo LGTM
- [x] QE LGTM

---
Eliminate remaining deprecations/aliases in page objects.

### CODE REVIEW

**Comment by 100stacks** [comment]
Updated `2.0.0-8 Release Notes (unreleased)`:
https://github.com/rackerlabs/encore-ui/releases/tag/untagged-40b13b67496b25ef9aab

Updated `2.0 Migration Guide`:
https://github.com/rackerlabs/encore-ui/wiki/2.0-Migration-Guide#v200-8-eliminate-deprecatedaliased-page-objects

**Comment by parlarjb** [comment]
LGTM

**Comment by CITguy** [comment]
@100stacks: please rebase and resubmit via an upstream branch

**Comment by Droogans** [comment]
Hm. It appears there was a rackerlabs branch pushed up as well.

https://github.com/rackerlabs/encore-ui/compare/2.x...FRMW-742-eliminate-deprecations-aliases-in-page-objects

**Pull request closed without merging**
