### PR TITLE
Demo site V2

### PR DESCRIPTION
**Pull request by ErnieAtLYD**
Looking for team feedback (copy, angular.js optimization) for the V2 style guide demo site. (rackerlabs.github.io/encore-ui/)

Going to continue submitting commits, especially those marked FIXME.

### CODE REVIEW

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/669/gallery.html)

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/669/gallery.html)

**Comment by glynnis** [comment]
LGTM! :tada: :tangerine: :tanabata_tree:

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/669/gallery.html)

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/669/gallery.html)

**Pull request merged**
