### PR TITLE
Visual regression

### PR DESCRIPTION
**Pull request by Droogans**
This replaces the full-screenshot visual regression of our Wraith job with a more fine-grained solution.

It uses Selenium (Protractor, really) to grab screenshots *while* running end to end tests. It supports the ability to take a screenshot of just a certain part of the screen, at various resolutions.

Here's what the different visual regression notifications look like, as well as a preview of the diffs.

## Wraith

screen shot 2015-05-13 at 13 30 08

screen shot 2015-05-13 at 13 31 00

## This stuff

screen shot 2015-05-13 at 13 31 58

screen shot 2015-05-13 at 13 32 36

You can see the full diff in github of the new stuff: https://github.com/rackerlabs/encore-ui-screenshots/pull/6/files

## Advantages

 - Manipulate the page in Selenium, take a screenshot, continue
   - Allows for extremely complicated scenarios that might need visual checks along the way
 - Automatically names them in an easily diff-able way
   - `{{browser}}/{{path/to/test/files}}/{{mocha-test-name}}/{{resolution}}-{{selectorName}}.png`
 - Leverages github's built-in image diff tools
 - Add one line of code to get all of this

## Disadvantages

 - Can only store ~25,000 screenshots in a github repo
   - however, by the time we reach 25k screenshots, this limit will likely be raised
 - Can only display the first 25 images in a github pull request
   - you can still pull it down and view all of them yourself, though
 - @comeatmebro will build many screenshot reports if there are multiple commits pushed to the PR
   - can feasibly reach 25k screenshots this way in a short amount of time
 - The screenshot naming convention is very verbose

More is discussed in the [rackerlabs/encore-ui-screenshots readme file](https://github.com/rackerlabs/encore-ui-screenshots).

The library that does most of the heavy lifting is at https://www.npmjs.com/package/snappit-mocha-protractor

### CODE REVIEW

**Comment by Droogans** [comment]
Don't merge this until I get the details worked out.

**Comment by Droogans** [comment]
Better....but still not working right. The branch name should match, but it says "master".

Also, @halkon shouldn't be committing these screenshots. Anyone know @comeatmebro's email address so that the commits show up under the bot? @rnreekez / @chriscantu?

**Comment by halkon** [comment]
Oh man... I'm gonna have sooo many commits.

**Comment by rnreekez** [comment]
@Droogans comeatmebro@users.noreply.github.com

**Comment by Droogans** [comment]
There's still some issues.

Does the grunt screenshot shell tasks account for when there are no visual differences? It should not fail when there's nothing to push up.

**Pull request closed without merging**
