### PR TITLE
docs(rxMisc): mark param as optional [skip ci]

### PR DESCRIPTION
**Pull request by CITguy**
Per post-merge [comment](https://github.com/rackerlabs/encore-ui/pull/1107/files#r36010268)

[ci skip] [skip ci]

### CODE REVIEW

**Comment by Droogans** [comment]
LGTM not sure if skipping CI is a thing or not but I'd like to know more.

Also thanks for picking this up for me.

**Comment by CITguy** [comment]
yeah, you can skip, but it needed to be in the commit message, not the PR description. oh well ¯\_(ツ)_/¯

**Comment by megalord** [comment]
LGTM

**Comment by chriscantu** [comment]
LGTM

LGTM

**Pull request merged**
