### PR TITLE
feat(rxNotify): Add ondismiss method to rxNotify

### PR DESCRIPTION
**Pull request by nickburns2006**

### CODE REVIEW

**Comment by halkon** [comment]
Closes: https://github.com/rackerlabs/encore-ui/issues/927

**Comment by nickburns2006** [comment]
@halkon, had to allow the `$interval` to invoke the `$apply` otherwise it wasn't firing the `ondismiss`.

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/933/gallery.html)

**Comment by parlarjb** [comment]
I like this idea. Did you contemplate doing it with a promise, instead of a callback? `.add` returns a `message` object right now, we could put a `$promise` attribute onto that object.

That's just a thought though. I'm fine with going the callback route if you think it'll get us everything we need.

**Comment by nickburns2006** [comment]
@parlarjb @halkon and I discussed this, and while I understand the thoughts of doing it as a promise, it doesn't make sense in a "do this on dismissal" architecture. I felt like setting things up to be $promise-based altered the architecture/behavior too drastically.

**Comment by parlarjb** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
