### PR TITLE
chore(rxPageObjects): Update docs README.md

### PR DESCRIPTION
**Pull request by jj4th**
JIRA: https://jira.rax.io/browse/FRMW-1331

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM
- [ ] Design LGTM
- [x] QE LGTM

This PR:
- Updates the examples in the `README.md` file. (Removes rxBreadcrumbs which no longer exists)
- Adds a note on extending Protractor API's `ElementFinder`.

### CODE REVIEW

**Comment by jj4th** [comment]
@Droogans should we just go ahead and combine this with the README.md in `utils/rx-page-objects`?  I'll submit an alternative PR for that.

**Comment by Droogans** [comment]
I feel like this represents 90% of what rx-page-objects is good at now. The other PR you've linked here is trying to push a selling point that has been dropped: reducing the amount of typing for basic activities, versus now which expects the user to implement more details for low level interactions.

**Comment by jj4th** [comment]
Moved this `README.md` file to the project root to replace that one.

**Comment by CITguy** [comment]
I'm not convinced that we should combine these two README's. They serve different purposes.  The one in the root should be for instruction around how to **develop** the page objects, while the other should be for instruction on how to **consume** the page objects.

**Comment by jj4th** [comment]
@CITguy While a compelling argument could be made that they /should/ serve two different purposes... in actuality they contained almost entirely the same content, with the one difference being that the content in the root README.md largely was no longer relevant.  Andrew and I both agreed that the edits I made to bring the root README.md examples up to date resulted in a lot of bad documentation that didn't really express anything useful.

**Comment by jj4th** [comment]
Offline discussion with @CITguy yielded that there was some confusion about which README.md was being retained, and what was being removed.  Additionally, we found a typedoc styled link in the markdown that needs to be removed now.

**Comment by parlarjb** [comment]
Vidyo LGTM

**Comment by CITguy** [comment]
@Droogans: can you provide your review, please?

**Comment by Droogans** [comment]
LGTM.

Does this need a design sign off?

**Comment by CITguy** [comment]
I'm gonna say, no. Merging.

**Pull request merged**
