### PR TITLE
Visual regression squashed

### PR DESCRIPTION
**Pull request by Droogans**
See https://github.com/rackerlabs/encore-ui/pull/938 for the original, unsquashed pull request.

### CODE REVIEW

**Comment by Droogans** [comment]
On hold until I can figure out if/when an encore 2.0 release can go out.

**Comment by TheNando** [comment]
Don't forget to document the 'Why?' and not just the 'How?'. Also, should vis-reg be its own test run, or is it included with the existing e3e suite?

**Comment by Droogans** [comment]
@glynnis @parlarjb this is now running both Chrome and Firefox screenshots.

**Comment by Droogans** [comment]
@parlarjb I just looked at how this is handling partial screenshots in Chrome. It's naming the file by the resolution of the screenshot, which is good...however, if the element renders outside of the visible area of the screen, it'll only grab the visible part. The name reflects this -- for instance, an 800x600 screenshot that only renders in the right half would get renamed to 400x600! This is bad because as the CSS is fixed to allow for the full 800x600 pixels to be visible, there would be a new screenshot created, instead of overwriting the old one.

This is going to require a pull request in the screenshot naming function, something I can get done soon and release and pull in later.

For now, let's stick with just Firefox.

**Comment by parlarjb** [comment]
LGTM

**Comment by Droogans** [comment]
Ok we have a new visual baseline let's see how travis handles pulling them down and running it again.

**Comment by Droogans** [comment]
@parlarjb the last visual regression check appeared to work just fine. We should make a PR fixing the breadcrumbs and seeing how it looks with a diff.

**Comment by TheNando** [comment]
This also looks good to me.

**Pull request merged**
