### PR TITLE
refactor(rxSortUtil): FRMW-413-convert to quark.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-413

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxSortableColumn.rxSortUtil` to Quark Service.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxSortUtil` Quark Service

### Demo Page
screen shot 2015-12-29 at 5 42 48 pm

### API Docs
screen shot 2015-12-29 at 4 55 31 pm

**Comment by glynnis** [comment]
Design LGTM

**Comment by CITguy** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
