### PR TITLE
refactor(rxPageTitle): FRMW-404-convert to Quark Service.

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-404

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
Refactor `rxPageTitle.rxPageTitle` to Quark Service.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxPageTitle` Quark Service

### Demo Page
screen shot 2016-01-14 at 5 39 47 pm

### API Docs
screen shot 2016-01-14 at 5 40 08 pm

**Comment by parlarjb** [comment]
LGTM

**Comment by CITguy** [comment]
LGTM

**Comment by ssalinas24** [comment]
LGTM

**Pull request merged**
