### PR TITLE
refactor(devicePaths): FRMW-378-refactor to Quark value

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-378

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM 

---
Refactor `config.devicePaths` to Quark value.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `devicePaths` Quark Value

### Demo Page
screen shot 2015-12-23 at 2 35 55 pm

### API Docs
screen shot 2015-12-23 at 2 35 35 pm

**Comment by glynnis** [comment]
Assuming that it's appropriate there's no demo or visual element here, giving this a Design LGTM :+1:

**Comment by CITguy** [comment]
LGTM

@halkon, is this something that would make more sense in the SVCS repo?

**Comment by halkon** [comment]
LGTM.....? :question: :grey_question: :dart: 
@CITguy yes, this definitely needs to be moved over into `svcs` under the `cloud` namespace

**Comment by parlarjb** [comment]
LGTM

**Comment by parlarjb** [comment]
Can we create a story for moving this to `svcs`?

**Comment by 100stacks** [comment]
@parlarjb, done :ok_hand: 

https://jira.rax.io/browse/FRMW-596 - Technical Spike: Review Quarks for Migration to Encore Services

**Pull request merged**
