### PR TITLE
chore(rxFloatingHeader): add Y tolerance to midways

### PR DESCRIPTION
**Pull request by CITguy**
Expanded upon #1229, to apply Y value tolerance to all checks.

> This isn't an issue on Travis, but when running tests locally, there is an issue where the floating header will be off by one pixel on higher resolution displays. This fix adds a tolerance around the location of the floating header during protractor tests to be +/- 2 pixels.

- [x] Dev LGTM
- [x] Dev LGTM
- [x] QE LGTM

### CODE REVIEW

**Comment by bry4n** [comment]
LGTM

**Comment by parlarjb** [comment]
What about building the tolerance stuff into the page object? i.e. something like

```
actual = encore.rxFloatingHeader.transformLocation(tr, 'y', { yTolerance: 2 });
expect(actual).to.eventually.be.within(actual.lower, actual.upper);
```

This way, if a product is using our page objects to test their own use of `rxFloatingHeader`, the API will make explicit that this sort of this can/should be done.

**Comment by parlarjb** [comment]
(I just noticed that the `expect(actual)` wouldn't work anymore above, but you get the general idea)

**Comment by parlarjb** [comment]
```
y = encore.rxFloatingHeader.transformLocation(tr, 'y', { yTolerance: 2 });
expect(y.actual).to.eventually.be.within(y.lower, y.upper);
```
maybe this instead

**Comment by CITguy** [comment]
I see what you're saying, it would make sense to add this to the default exercise options if it needs changed/overridden for edge cases. I'll update this.

**Comment by CITguy** [comment]
So, after looking at the page object, there are a few things to note:

1. All existing functions in `encore.rxFloatingHeader` will be moved to `encore.rxMisc` (with aliases to support backward compatibility), because they are utility functions that are not specific to floating headers. I will do this in the current PR.
2. The rxFloatingHeader page object needs refactored to act more like a page object (`encore.rxFloatingHeader.initialize()`) rather than a namespace for utility functions. (Captured in [FRMW-256](https://jira.rax.io/browse/FRMW-256))
3. Refactoring the location functions to use tolerances is not a simple undertaking, outside of the scope of this PR, and should be performed in a separate story (Captured in [FRMW-255](https://jira.rax.io/browse/FRMW-255))

**Comment by parlarjb** [comment]
LGTM

**Comment by Droogans** [comment]
Updated https://github.com/rackerlabs/encore-ui/issues/978 to reflect these deprecation notices.

@parlarjb I don't like the idea of passing in an optional argument that alters the return value. I think it makes sense to mark your tolerance values in the test if you need a tolerance (so far, it hasn't affected phone-ui, so there's that).

LGTM.

**Pull request merged**
