### PR TITLE
Drop jshint jscs

### PR DESCRIPTION
**Pull request by Droogans**
JIRA: https://jira.rax.io/browse/FRMW-705

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM

### CODE REVIEW

**Comment by 100stacks** [comment]
Thanks for going over the PR! LGTM 👍

**Comment by CITguy** [comment]
I'm walking through this PR, now.

**Comment by parlarjb** [comment]
❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ LGTM

**Comment by 100stacks** [comment]
@Droogans, just thought about this...do we need to update the documentation? https://github.com/rackerlabs/encore-ui/blob/f4d90873098659b0cfd464e118daadf3002222ab/guides/js-styleguide.md#jshint-and-jscs

**Pull request merged**
