### PR TITLE
refactor(color): Change hex codes to lowercase

### PR DESCRIPTION
**Pull request by glynnis**
JIRA: https://jira.rax.io/browse/FRMW-542

### LGTMs
- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

### Before
screen shot 2016-03-29 at 1 51 26 pm

### After
screen shot 2016-03-29 at 1 51 39 pm

### CODE REVIEW

**Comment by CITguy** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Comment by glynnis** [comment]
@ssalinas24 when you get a chance can you give this a once-over? I think it should be pretty quick and easy given the scope of the story.

**Comment by ssalinas24** [comment]
LGTM

**Pull request merged**
