### PR TITLE
fix(bux): FRMW-128-Unbreakable long page titles

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-128 - Handling long, unbreakable page titles

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

---
* Wrap unbreakable long values for `.page-title`
* Wrap unbreakable long values for `.page-subtitle`
* Fix `.status-tag` not flowing properly in the title

### CODE REVIEW

**Comment by 100stacks** [comment]
Before:
* Notice the *Title* and *Subtitle* not wrapping.
* Notice *Status Tag* overlap

screen shot 2015-10-14 at 4 35 47 pm

**Comment by 100stacks** [comment]
After:

screen shot 2015-10-14 at 5 08 51 pm

**Comment by bry4n** [comment]
LGTM

**Comment by CITguy** [comment]
@100stacks, can you post before/after screenshots from Firefox? I remember there being inconsistencies between Chrome and Firefox when I created this story.

**Comment by 100stacks** [comment]
Before on Firefox 41:

screen shot 2015-10-15 at 10 00 09 am

**Comment by 100stacks** [comment]
After on Firefox 41:

screen shot 2015-10-15 at 10 02 01 am

**Comment by 100stacks** [comment]
@CITguy  Firefox 41 screenshots provided. :+1:

**Comment by glynnis** [comment]
LGTM

**Comment by CITguy** [comment]
@100stacks, LGTM, but can you resubmit a PR against a branch on upstream? I'd like to get the visual regression to check this.

**Comment by CITguy** [comment]
Closing, #1315 captures same code for visual regression.

**Pull request closed without merging**
