### PR TITLE
docs(rxSortableColumn): Remove unnecessary import.

### PR DESCRIPTION
**Pull request by megalord**
JIRA: n/a

### LGTMs
- [x] Dev LGTM
- [x] Dev+Vidyo LGTM
- [ ] QE LGTM

### CODE REVIEW

**Comment by parlarjb** [comment]
LGTM

**Comment by 100stacks** [comment]
LGTM

**Comment by glynnis** [comment]
Removing the "Design LGTM" checkbox -- don't think my review is needed here.

**Comment by 100stacks** [comment]
@megalord, I don't think we need QE either since it's touching the demo/docs.  👍 💯

**Pull request merged**
