### PR TITLE
refactor(quarks): FRMW-386 rxAppRoutes.rxAppRoutes FRMW-387 urlUtils

### PR DESCRIPTION
**Pull request by 100stacks**
JIRA: https://jira.rax.io/browse/FRMW-386 (`rxAppRoutes.rxAppRoutes`)
JIRA: https://jira.rax.io/browse/FRMW-387 (`rxAppRoutes.urlUtils`)

- [x] Dev LGTM
- [x] Dev LGTM

---
Refactored `rxAppRoutes.rxAppRoutes` and `rxAppRoutes.urlUtils` to Quark Services.  This PR removes `rxAppRoutes` component.

### CODE REVIEW

**Comment by 100stacks** [comment]
## `rxAppRoutes` Quark Service

### Demo Page
screen shot 2016-02-08 at 11 34 58 am

### API Docs
screen shot 2016-02-08 at 11 37 38 am

**Comment by 100stacks** [comment]
## `urlUtils` Quark Service

### Demo Page
screen shot 2016-02-08 at 10 44 17 am


### API Docs
screen shot 2016-02-08 at 10 44 32 am

**Comment by CITguy** [comment]
LGTM

**Comment by parlarjb** [comment]
LGTM

**Pull request merged**
