### PR TITLE
chore(ngAnnotate): Upgrade to 0.10.0

### PR DESCRIPTION
**Pull request by parlarjb**
Trying to do a release, and we're running into https://github.com/olov/ng-annotate/issues/139 Updating our grunt-ng-annotate (which brings in a new ngAnnotate) fixes it.

### CODE REVIEW

**Comment by CITguy** [comment]
LGTM

**Comment by megalord** [comment]
:+1:

**Comment by halkon** [comment]
LGTM

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/869/gallery.html)

**Pull request merged**
