### PR TITLE
fix(links): Fix demo links

### PR DESCRIPTION
**Pull request by bry4n**
For Issue https://github.com/rackerlabs/encore-ui/issues/1338

Fix all demo links (`/#/components/...` -> `/encore-ui/#/components/...`)

* [x] Dev LGTM
* [x] Dev LGTM

### CODE REVIEW

**Comment by 100stacks** [comment]
@bry4n when we add `/encore-ui/` it won't point to the demo pages on local builds.

So...
`http://localhost:9001/#/components/rxModalAction` 
works, and...
`http://localhost:9001/encore-ui/#/components/rxModalAction` 
will not.

It appears the deployed environment requires `/encore-ui/`, while local environment doesn't.  Any thoughts on how to handle both?

**Comment by CITguy** [comment]
Sadly, these links will not work locally without the following proxy added to `grunt-tasks/options/connect.js`

```javascript
{
    context: '/encore-ui',
    host: 'localhost',
    port: 9001,
    rewrite: {
        '/encore-ui', '/'
    }
}
```

@bry4n, please add the above proxy to the `proxies` object in `grunt-tasks/options/connect.js`.

**Comment by CITguy** [comment]
Additionally, please update the following links as well.

* https://github.com/rackerlabs/encore-ui/blob/master/src/typeahead/typeahead.js#L21
* https://github.com/rackerlabs/encore-ui/blob/master/src/rxButton/rxButton.js#L13

**Comment by bry4n** [comment]
@CITguy @100stacks added new proxy to connect config and updated two API docs.

**Comment by 100stacks** [comment]
@bry4n looks great! LGTM :+1:

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
