### PR TITLE
docs(styleguide): update rxMetadata usage

### PR DESCRIPTION
**Pull request by CITguy**
JIRA: https://jira.rax.io/browse/FRMW-101

- [x] Dev LGTM
- [x] Dev LGTM
- [x] Design LGTM

### CODE REVIEW

**Comment by CITguy** [comment]
## Styleguide - Descriptions/Metadata

### Before
sg-metadata-before

### After
sg-metadata-after

**Comment by CITguy** [comment]
## Styleguide - Layout 1 

### Before
sg-layout-1-before

### After
sg-layout-1-after

**Comment by CITguy** [comment]
## Styleguide - Tables - Nested Metadata

### Before
sg-tables-nested-metadata-before

### After
sg-tables-nested-metadata-after

**Comment by CITguy** [comment]
## Styleguide - Layouts - Common Layouts

### Before
screen shot 2015-08-06 at 4 15 27 pm

### After
screen shot 2015-08-06 at 4 15 13 pm

**Comment by parlarjb** [comment]
LGTM

**Comment by glynnis** [comment]
@CITguy Can you update to include https://github.com/rackerlabs/encore-ui/pull/1126?

**Comment by CITguy** [comment]
@glynnis, sure can. I'll get that updated shortly.

**Comment by CITguy** [comment]
Updated. "Styleguide - Basic - Descriptions/Metadata" "After" screenshot updated.

**Comment by Droogans** [comment]
@CITguy once this gets LGTM'd and is ready to merge, can you close this and reopen it under `rackerlabs:metadata-styleguide`? You've altered the demo that is being tracked under visual regression checks.

**Comment by glynnis** [comment]
LGTM :icecream: :shaved_ice: :cherries:

**Comment by megalord** [comment]
LGTM

**Comment by Droogans** [comment]
@CITguy LGTM can you push this to upstream for a visual regression?

**Comment by CITguy** [comment]
@Droogans, i'm on it

**Pull request closed without merging**
